### ISSUE TITLE
Deployment's errors - 409 and 400

### ISSUE THREAD

**Issue by fabiob77** [oracle-quickstart/oci-landing-zones#10]
Error 1: 
 
│ Error: 409-NotAuthorizedOrResourceAlreadyExists, Compartment -:  ocid1.tenancy.oc1..aaaaaaaatqt3lnlrwm72u7uqzfexy3vbz4rr4k67vmjizmvhll5smdg5v7ka already attached
│ Suggestion: The resource is in a conflicted state. Please retry again or contact support for help with service: Cloud Guard Target
│ Documentation: [https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/cloud_guard_target](https://urldefense.com/v3/__https:/registry.terraform.io/providers/oracle/oci/latest/docs/resources/cloud_guard_target__;!!ACWV5N9M2RV99hQ!IfCA3y9OZQXNJTBZYLJjXDNLFqVCENyy7fUB7up-boG9V-pqBRZAOh-fiCEpEoAQwmwc96tTkC_0wRD0RFtJ6M3AQq-bm33yVg$)
│ API Reference: https://docs.oracle.com/iaas/api/#/en/cloud-guard/20200131/Target/CreateTarget
│ Request Target: POST https://cloudguard-cp-api.ap-sydney-1.oci.oraclecloud.com/20200131/targets
│ Provider version: 4.96.0, released on 2022-10-05. This provider is 27 Update(s) behind to current.
│ Service: Cloud Guard Target
│ Operation Name: CreateTarget
│ OPC request ID: 8a04ed11a791c5dc7758743b734a769a/66C548705780D62AD0F1A3A172A1B1F2/91989B9C6239D5BE42B2DE89388EA59B
│
│
│   with module.nonprod_environment.module.security.module.cloud_guard[0].oci_cloud_guard_target.cloud_guard_target,
│   on ..\..\modules\cloud-guard\[main.tf](https://urldefense.com/v3/__http:/main.tf__;!!ACWV5N9M2RV99hQ!IfCA3y9OZQXNJTBZYLJjXDNLFqVCENyy7fUB7up-boG9V-pqBRZAOh-fiCEpEoAQwmwc96tTkC_0wRD0RFtJ6M3AQq8PvPHGtQ$) line 18, in resource "oci_cloud_guard_target" "cloud_guard_target":
│   18: resource "oci_cloud_guard_target" "cloud_guard_target" {
│

Error 2 : 

│ Error: 400-InvalidParameter, vaultType Invalid vault type Virtual. Valid values are [VirtualPrivate]
│ Suggestion: Please update the parameter(s) in the Terraform config as per error message vaultType Invalid vault type Virtual. Valid values are [VirtualPrivate]
│ Documentation: [https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/kms_vault_replica](https://urldefense.com/v3/__https:/registry.terraform.io/providers/oracle/oci/latest/docs/resources/kms_vault_replica__;!!ACWV5N9M2RV99hQ!IfCA3y9OZQXNJTBZYLJjXDNLFqVCENyy7fUB7up-boG9V-pqBRZAOh-fiCEpEoAQwmwc96tTkC_0wRD0RFtJ6M3AQq_yGbENnA$)
│ API Reference:
│ Request Target: POST https://kms.ap-sydney-1.oraclecloud.com/20180608/vaults/ocid1.vault.oc1.ap-sydney-1.dbsccskoaagdo.abzxsljrrfolvrivx3mrrvizbjunczfrrwseflngrmvnsojszu3gv3hffyiq/actions/createReplica
│ Provider version: 4.96.0, released on 2022-10-05. This provider is 27 Update(s) behind to current.
│ Service: Kms Vault Replica
│ Operation Name: CreateVaultReplica
│ OPC request ID: 2d3c01a3b325697d290238ca266bd0a6/71675FD22C6E5470E5E1ADE989ECF777/0079CAC643E530431BEF2B21C2AAD95F
│
│
│   with module.prod_environment.module.security.module.vault[0].oci_kms_vault_replication.replication[0],
│   on ..\..\modules\vault\[main.tf](https://urldefense.com/v3/__http:/main.tf__;!!ACWV5N9M2RV99hQ!IfCA3y9OZQXNJTBZYLJjXDNLFqVCENyy7fUB7up-boG9V-pqBRZAOh-fiCEpEoAQwmwc96tTkC_0wRD0RFtJ6M3AQq8PvPHGtQ$) line 15, in resource "oci_kms_vault_replication" "replication":
│   15: resource "oci_kms_vault_replication" "replication" {

**Comment by paulmuah** [comment]
Hey @fabiob77 , we are tracking this issue under LANZ-1472

**Comment by paulmuah** [comment]
Resolved by @VinayKumar611
