### ISSUE TITLE
Error: 400-InvalidParameter, Compartment {ocid1.compartment.oc1....} does not exist or is not part of the policy compartment subtree

### ISSUE THREAD

**Issue by fpacilio** [oracle-quickstart/oci-landing-zones#100]
Hi,
I am trying to deploy the OELZ version  [](https://github.com/oracle-quickstart/oci-landing-zones/releases/tag/v2.1.2)[https://github.com/oracle-quickstart/oci-landing-zones/releases/tag/v2.1.2](https://urldefense.com/v3/__https:/github.com/oracle-quickstart/oci-landing-zones/releases/tag/v2.1.2__;!!LQkDIss!WHAdcyl37MPMbulM3AXqNFVuub6BSubchwTxdW9WGzSQxeRdrVpcj0RSyHMA-9HIvkDcLWduVfBzKBu-h589tmCbBqghqA$) 
<img width="805" alt="OELZ-version" src="https://github.com/oracle-quickstart/oci-landing-zones/assets/12696646/f3bf3ca5-44a1-49c5-b56e-53686aa939b7"> with Resouce Manager.

It failed during the "module.prod_environment.module.workload.module.workload_osms_dg_policy.oci_identity_policy.policy," creation.

Below is the plan and error log.

**PLAN:**
 # module.prod_environment.module.workload.module.workload_osms_dg_policy.oci_identity_policy.policy will be created
  + resource "oci_identity_policy" "policy" {
      + ETag           = (known after apply)
      + compartment_id = "ocid1.compartment.oc1..aaaaaaaawmbt6l4wgvf6zdwchpfds3pni2egwt5cujfxshgy4ulax2rb4dcq"
      + defined_tags   = (known after apply)
      + description    = "Workload OCI Landing Zone OS Management Service Dynamic Group Policy"
      + freeform_tags  = (known after apply)
      + id             = (known after apply)
      + inactive_state = (known after apply)
      + lastUpdateETag = (known after apply)
      + name           = "OCI-P-ELZ-Workload1-OSMS-DG-Policy"
      + policyHash     = (known after apply)
      + state          = (known after apply)
      + statements     = [
          + "Allow dynamic-group OCI-P-ELZ-Workload1-DG to read instance-family in compartment ocid1.compartment.oc1..aaaaaaaawmbt6l4wgvf6zdwchpfds3pni2egwt5cujfxshgy4ulax2rb4dcq",
          + "Allow dynamic-group OCI-P-ELZ-Workload1-DG to use osms-managed-instances in compartment ocid1.compartment.oc1..aaaaaaaawmbt6l4wgvf6zdwchpfds3pni2egwt5cujfxshgy4ulax2rb4dcq",
        ]
      + time_created   = (known after apply)
      + version_date   = (known after apply)
    }

**Error log:**
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] Error: 400-InvalidParameter, Compartment {ocid1.compartment.oc1..aaaaaaaaacxbinb6bzfo36g4i55radlsepp2pb53aekcx6x3cqoj72udt65q} does not exist or is not part of the policy compartment subtree
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] Suggestion: Please update the parameter(s) in the Terraform config as per error message Compartment {ocid1.compartment.oc1..aaaaaaaaacxbinb6bzfo36g4i55radlsepp2pb53aekcx6x3cqoj72udt65q} does not exist or is not part of the policy compartment subtree
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/identity_policy 
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] API Reference: https://docs.oracle.com/iaas/api/#/en/identity/20160918/Policy/CreatePolicy 
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] Request Target: POST https://identity.eu-milan-1.oci.oraclecloud.com/20160918/policies 
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] Provider version: 5.1.0, released on 2023-06-13. This provider is 13 Update(s) behind to current. 
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] Service: Identity Policy 
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] Operation Name: CreatePolicy 
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] OPC request ID: 534cea82b65ffa33a5559b4898870d0b/FFDE662416A3FDCFE7F6BC31689BCF76/F0F0C07537FCD17CDFE25B91C0522329 
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] 
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] 
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO]   with module.nonprod_environment.module.workload.module.workload_osms_dg_policy.oci_identity_policy.policy,
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO]   on ../../modules/policies/main.tf line 9, in resource "oci_identity_policy" "policy":
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO]    9: resource "oci_identity_policy" "policy" {
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] 
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] 
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] Error: 400-InvalidParameter, Compartment {ocid1.compartment.oc1..aaaaaaaawmbt6l4wgvf6zdwchpfds3pni2egwt5cujfxshgy4ulax2rb4dcq} does not exist or is not part of the policy compartment subtree
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] Suggestion: Please update the parameter(s) in the Terraform config as per error message Compartment {ocid1.compartment.oc1..aaaaaaaawmbt6l4wgvf6zdwchpfds3pni2egwt5cujfxshgy4ulax2rb4dcq} does not exist or is not part of the policy compartment subtree
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/identity_policy 
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] API Reference: https://docs.oracle.com/iaas/api/#/en/identity/20160918/Policy/CreatePolicy 
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] Request Target: POST https://identity.eu-milan-1.oci.oraclecloud.com/20160918/policies 
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] Provider version: 5.1.0, released on 2023-06-13. This provider is 13 Update(s) behind to current. 
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] Service: Identity Policy 
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] Operation Name: CreatePolicy 
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] OPC request ID: bd820545a1472ab2b697394e0091ab98/C2CFD28C6FCD5C5381D4E0FE17109682/F3A8FC75899AB9D4307E7A9AB7300706 
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] 
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] 
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO]   with module.prod_environment.module.workload.module.workload_osms_dg_policy.oci_identity_policy.policy,
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO]   on ../../modules/policies/main.tf line 9, in resource "oci_identity_policy" "policy":
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO]    9: resource "oci_identity_policy" "policy" {
2023/09/15 09:25:30[TERRAFORM_CONSOLE] [INFO] 
2023/09/15 09:25:31[TERRAFORM_CONSOLE] [INFO]

**Comment by Reply-emgargano** [comment]
The statements of the policy are wrong. The correct ones are:

statements = [
"Allow dynamic-group OCI-P-ELZ-Workload1-DG to read instance-family in compartment **in** ocid1.compartment.oc1..aaaaaaaawmbt6l4wgvf6zdwchpfds3pni2egwt5cujfxshgy4ulax2rb4dcq",
"Allow dynamic-group OCI-P-ELZ-Workload1-DG to use osms-managed-instances in compartment **in** ocid1.compartment.oc1..aaaaaaaawmbt6l4wgvf6zdwchpfds3pni2egwt5cujfxshgy4ulax2rb4dcq",
]

The correct syntax is explained here: https://docs.oracle.com/en-us/iaas/Content/Identity/Concepts/policysyntax.htm#:~:text=To%20specify%20a%20compartment%20by%20OCID

Needs to be changed the policy statement in the file "security.tf" of the "elz-workload", specifically the "local.osms_dg_policy_workload.statements"

**Comment by VinayKumar611** [comment]
Fixed the issue on latest release v2.2.0.
