### ISSUE TITLE
logSourceIdentifier size must be between 1 and 512

### ISSUE THREAD

**Issue by sivachunduru** [oracle-quickstart/oci-landing-zones#11]
1. While terraform re-apply, it has thrown an error stating "logGroups are not empty".
2. Then, purged the storage in logGroups of both Prod and Non-Prod environments.
3. Now, it throws the error "400-InvalidParameter target.logSourceIdentifier size must be between 1 and 512"
![image-error](https://user-images.githubusercontent.com/12733420/232429225-d2c8c365-bc97-4797-93bd-9eb4d32ef942.png)

**Comment by jason-chong** [comment]
@sivachunduru were you able to continue on with your deployment after the recommended items to delete?

**Comment by paulmuah** [comment]
Resolved by @VinayKumar611

**Comment by paulmuah** [comment]
Issue resolved by @VinayKumar611
