### ISSUE TITLE
OCI Network Firewall Code issue

### ISSUE THREAD

**Issue by preetomgoswamioracle** [oracle-quickstart/oci-landing-zones#116]
Hi,

Looks like there is a problem in the portion of the code where the network firewall creation is invoked. 
There is a  cyclic dependency.
Inside ‘templates/elz-environment’ folder - the ‘network’ module refers ‘logging’ module (in 'main.tf') AND ‘logging’ module refers to ‘network’ module (in 'logging.tf').
Appreciate any guidance on the same.

Regards,
Preetom

**Comment by VinayKumar611** [comment]
Hi @preetomgoswamioracle , 

We designed our solution so that the cyclic error would not occur and thoroughly tested the solution(not seen the cyclic error). Please try the Terraform apply again and let us know the Terraform error.

Regards, 
Vinay Kumar

**Comment by preetomgoswamioracle** [comment]
Thanks @VinayKumar611 for your quick support. The issue is now resolved!

**Comment by VinayKumar611** [comment]
Thanks @preetomgoswamioracle !
