### ISSUE TITLE
Database Admins need higher IAM privileges

### ISSUE THREAD

**Issue by sivachunduru** [oracle-quickstart/oci-landing-zones#15]
The Database admins need "**manage**" policies in the workload compartment, not just "**read**" permissions.

"Allow group ${var.identity_domain_name}/${local.group_names["database_admin_group_name"]} to **read** autonomous-database-family in compartment ${module.workload_compartment.compartment_name}",
      "Allow group ${var.identity_domain_name}/${local.group_names["database_admin_group_name"]} to **read** database-family in compartment ${module.workload_compartment.compartment_name}",

**Comment by paulmuah** [comment]
Hey @spavlusieva , we're tracking this issue under LANZ-1555
