### ISSUE TITLE
manage_identity_domain.py file not required under identity-domain module

### ISSUE THREAD

**Issue by sivachunduru** [oracle-quickstart/oci-landing-zones#16]
As there is a new module (identity-domain-groups) introduced, the scripts folder under "identity-domain" module can be removed. The python script is already moved to "identity-domain-groups" module.

**Comment by paulmuah** [comment]
Hey @spavlusieva, we're tracking this issue under LANZ-1556.

**Comment by paulmuah** [comment]
Issue closed by @VinayKumar611. Python dependency removed from the code.
