### ISSUE TITLE
Break-glass user email should be optional in ORM stack template

### ISSUE THREAD

**Issue by chanstev** [oracle-quickstart/oci-landing-zones#17]
- Break-glass users should be optional as stated in the [documentation](https://github.com/oracle-quickstart/oci-landing-zones/blob/master/templates/enterprise-landing-zone/README.md). But it is mandatory in the ORM stack template
- The label of the field is also wrong. There are 2 "Enable Compartment Delete" in the IAM Variables, but one of them is actually asking for Breakglass user

![Screenshot 2023-04-28 at 12 10 39](https://user-images.githubusercontent.com/22254955/235133513-90fa4143-e3b2-4ecc-b00a-8c6331499ede.png)
![Screenshot 2023-04-28 at 12 40 28](https://user-images.githubusercontent.com/22254955/235138457-c38210d4-7402-4c4f-a4e6-20a6f4dd8a6b.png)

**Comment by paulmuah** [comment]
Hey @chanstev  we're tracking this issue under LANZ-1559. We will keep you updated with progress.

**Comment by VinayKumar611** [comment]
Hey @chanstev , 

Break-glass user email variable is mandatory. We had updated our documentation and planning to release this fix main version 2.1.2.

**Comment by VinayKumar611** [comment]
Hi @chanstev , 

Break-glass user email is mandatory, updated the CONFIGURATION.md in the latest version v2.1.2
