### ISSUE TITLE
wrong link to Identity Federation

### ISSUE THREAD

**Issue by hslange** [oracle-quickstart/oci-landing-zones#174]
In the [Architecture Guide](https://github.com/oracle-quickstart/oci-landing-zones/blob/main/Official_Documentation/OELZ_Baseline_Deployment/Architecture_Guide.md), section Identity, there is a paragraph on "Federating with Microsoft Active Directory".
The information and [link provided](https://docs.oracle.com/en-us/iaas/Content/Identity/Tasks/federatingADFS.htm) relate to Federating with Microsoft Active Directory for OCI IAM **without** Identiy Domains. Please update the documentation to federation with AD for IAM **with** Identity domains.

**Comment by VinayKumar611** [comment]
Hi @hslange , 

We have added the following as you suggested in our Architecture Guide. 

For more information about federating with 3rd party Identity Providers with IAM Identity domain. [Managing Identity Providers](https://docs.oracle.com/en-us/iaas/Content/Identity/identityproviders/manage-identity-providers.htm#manage-identity-providers).

The Architecture Guide is updated in the Integration Branch. 
https://github.com/oracle-quickstart/oci-landing-zones/blob/integration/Official_Documentation/OELZ_Baseline_Deployment/Architecture_Guide.md
