### ISSUE TITLE
service connector names interchanged

### ISSUE THREAD

**Issue by hslange** [oracle-quickstart/oci-landing-zones#176]
In file [elz-logging/main.tf](https://github.com/oracle-quickstart/oci-landing-zones/blob/main/templates/elz-logging/main.tf) several service connectors are created.
However, the "audit_log_service_connector" gets the display name of the "default service connector" and the "default_log_service_connector" gets the name of the "audit_log_service_connector".
See the code snippet below:

**audit_log_service_connector** = {
    display_name  = "${var.resource_label}_${var.environment_prefix}_**defaultLogs**_standard"
    source_kind   = "logging"
    target_kind   = "objectStorage"
    log_group_id  = "_Audit_Include_Subcompartment"
    target_bucket = local.**audit_log**_bucket.name
  }

  **default_log_service_connector** = {
    display_name  = "${var.resource_label}_${var.environment_prefix}_**auditLogs**_standard"
    source_kind   = "logging"
    target_kind   = "objectStorage"
    target_bucket = local.**default_log**_bucket.name
  }

**Comment by VinayKumar611** [comment]
Hi @hslange , 

Thanks for reporting issue. We had replicated the issue and working on the fix . We will provide the update on this asap.

**Comment by VinayKumar611** [comment]
Hi @hslange , 

We fixed the issue provided, and now this fix is in the Integration Branch. Please take the latest code from the integration branch.

**Comment by hslange** [comment]
Thanks, looks good.
