### ISSUE TITLE
TF modules and Templates

### ISSUE THREAD

**Issue by chanstev** [oracle-quickstart/oci-landing-zones#19]
Suggest to move the reusable modules under ["modules" folder](https://github.com/oracle-quickstart/oci-landing-zones/tree/master/modules) (i.e. "templates" with "elz-") and leave different landing zone templates in the ["templates" folder](https://github.com/oracle-quickstart/oci-landing-zones/tree/master/templates) (i.e. [enterprise-landing-zone](https://github.com/oracle-quickstart/oci-landing-zones/tree/master/templates/enterprise-landing-zone), [freetrial-landing-zone](https://github.com/oracle-quickstart/oci-landing-zones/tree/master/templates/freetrial-landing-zone)). It would be more align with the [terraform best practices](https://developer.hashicorp.com/terraform/language/modules/develop/structure) and [oracle's terraform module template](https://github.com/oracle-terraform-modules/module-template) as well. The landing zone templates can serve as an example how those elz modules can be used for constructing a custom landing zone. So that additional landing zone templates using elz modules can be contributed by the community.

![Screenshot 2023-04-28 at 13 06 32](https://user-images.githubusercontent.com/22254955/235143304-9da8ee21-3144-4ede-9f28-77263c54a13a.png)

**Comment by paulmuah** [comment]
Hey @chanstev, this structure is by design. We opted for this structure to keep the hierarchy flatter. We are opened to revisit this structure in the future.
