### ISSUE TITLE
osms dynamic group for Workload expansion

### ISSUE THREAD

**Issue by sivachunduru** [oracle-quickstart/oci-landing-zones#24]
There is a dynamic group osms_dynamic_group that has an entry for default workload compartment.

instance.compartment.id = '${module.prod_environment.workload_compartment_id}'

Isn't it required for workload expansion also (for every new workload compartment)?

Or, just having an entry about LZ home compartment id is enough?

**Comment by paulmuah** [comment]
Hey @sivachunduru  we're tracking this issue under LANZ-1570. We will keep you updated with progress.

**Comment by VinayKumar611** [comment]
Hi @sivachunduru , 

 Added New Variable "workload_name_prefix" to define the Workload Name in the latest version v2.1.2
