### ISSUE TITLE
Where is the deploy to cloud button for resource manager ?

### ISSUE THREAD

**Issue by MarcGueury** [oracle-quickstart/oci-landing-zones#4]
Where is the deploy to cloud button for resource manager ??

See the doc that refers to it.

**Comment by paulmuah** [comment]
Hey MarcGueury,
Many thanks for your feedback and thanks for using the service. The Deploy to Resource Manager button will appear soon. We are completing the Schema.yml for ORM and as soon as that is done, we will have the option to run directly via Resource Manager.

~Paul

**Comment by paulmuah** [comment]
Hey MarcGueury,
Many thanks for your feedback and thanks for using the service. The Deploy to Resource Manager button will appear soon. We are completing the Schema.yml for ORM and as soon as that is done, we will have the option to run directly via Resource Manager.

~Paul

**Comment by jason-chong** [comment]
@MarcGueury we put the deploy to oci button (link) on the readme.
