### ISSUE TITLE
Ability to toggle off spoke components like db, web, app

### ISSUE THREAD

**Issue by mike-leuer** [oracle-quickstart/oci-landing-zones#42]
What if we want a blank slate or only want one component. I dont want to take up subnets I am not using.  I only want to use app for my subnets.

**Comment by mike-leuer** [comment]
I know I can manipulate the code, but making it modular and ability to turn off and on services in template would be nice to have.

You already sort of do this with your option of a workload.

**Comment by paulmuah** [comment]
Hey @mike-leuer, by default, those DB, Web and App are on. Again, I have created a ticket for our roadmap to see if we can  incorporate this feature request into our roadmap.  The tracking for this is **ISSUE1944**
