### ISSUE TITLE
Cloud Guard Target not working

### ISSUE THREAD

**Issue by mike-leuer** [oracle-quickstart/oci-landing-zones#45]
Now cloud guard is not working on a fresh tenancy. Nothing changed. 

```
Service: Cloud Guard Target
Operation Name: CreateTarget
OPC request ID: 
  with module.nonprod_environment.module.security.module.cloud_guard[0].oci_cloud_guard_target.cloud_guard_target,
  on ../../modules/cloud-guard/main.tf line 18, in resource "oci_cloud_guard_target" "cloud_guard_target" 
  18: resource "oci_cloud_guard_target" "cloud_guard_target" {
Error: 404-NotAuthorizedOrNotFound, Authorization failed or requested resource not found.

```

**Comment by jmalbarranORA** [comment]
I have the same error a few minutes ago, and I intially suspected that I forgot to delete the targets from my previous test. In any case, after reapply it worked (and created the 2 targets)

**Comment by paulmuah** [comment]
Greeting @mike-leuer. I'm following up to see if the fix suggested by @jmalbarranORA  resolved the issue.

**Comment by mike-leuer** [comment]
Re-deploying worked.
