### ISSUE TITLE
Cannot deploy when tenancy is not DEFAULT in .oci/config

### ISSUE THREAD

**Issue by jmalbarranORA** [oracle-quickstart/oci-landing-zones#49]
Related with issue #12 

I create this issue as previous step to create the pull request.

If I try to deploy enterprise landing zone from local terraform in my PC.
I have multiple profiles in my .oci/config
The deployment try to use DEFAULT config when creating IAM groups, and generate error in the /oci-landing-zones/modules/identity-domain-group/scripts/manage_identity_domain.py script.

Actions to do: 
- Change line 26 of python script, to build the config based in parameter
- Change provioner in line 17 of main.tf (/oci-landing-zones/modules/identity-domain-group/main.tf) to pass the parameters

**Comment by jmalbarranORA** [comment]
Hope it works!

Please, remind I have not tested in ORM neither freetier.

--
[Oracle]
Jose Manuel Albarrán
Mobile: +34 667 697 352
Paseo de la Castellana 81, 28046, Madrid, Spain



De: paulmuah ***@***.***>
Fecha: lunes, 12 de junio de 2023, 15:07
Para: oracle-quickstart/oci-landing-zones ***@***.***>
CC: Jose Manuel Albarran Segoviano ***@***.***>, Mention ***@***.***>
Asunto: [External] : Re: [oracle-quickstart/oci-landing-zones] Cannot deploy when tenancy is not DEFAULT in .oci/config (Issue #49)

Hey @jmalbarranORA<https://urldefense.com/v3/__https:/github.com/jmalbarranORA__;!!ACWV5N9M2RV99hQ!N7lSduPaKSX8Jkvxi5e6RA4l80_sniVLkPuSgWPzJkgabFXNqWxyDfcAgd5Tm1_BzDpwdnOno2sZZ-hvJCvLv7Dcviw$> . Many thanks for the contribution.

**Comment by paulmuah** [comment]
@jmalbarranORA, the Python script dependency is removed in the current release.
