### ISSUE TITLE
Spoke multiple regions 

### ISSUE THREAD

**Issue by mike-leuer** [oracle-quickstart/oci-landing-zones#55]
It would nice to have a module for a spoke in different region. That hub would peer to the hub.

**Comment by paulmuah** [comment]
Many thankd for the feedback, @mike-leuer. Will discuss with my product team the possibility.

**Comment by paulmuah** [comment]
Hey @mike-leuer, this is relating to Multi-region deployment. Again, the PM is reviewing for backlog prioritization.
