### ISSUE TITLE
4.96.0 -->  5.1.0 Error

### ISSUE THREAD

**Issue by mike-leuer** [oracle-quickstart/oci-landing-zones#56]
Trying to use the same stack with the latest code. I am getting this error when using the ui stack. 

```
Getting providers from hashicorp registry and/or custom terraform providers
Initializing modules...
Initializing provider plugins...
- Reusing previous version of oracle/oci from the dependency lock file
- Reusing previous version of hashicorp/random from the dependency lock file
- Reusing previous version of hashicorp/time from the dependency lock file
- Reusing previous version of hashicorp/null from the dependency lock file
- Installing hashicorp/null v3.2.1...
- Installed hashicorp/null v3.2.1 (signed by HashiCorp)
- Installing hashicorp/random v3.5.1...
- Installed hashicorp/random v3.5.1 (signed by HashiCorp)
- Installing hashicorp/time v0.9.1...
- Installed hashicorp/time v0.9.1 (signed by HashiCorp)
Error: Failed to query available provider packages
Could not retrieve the list of available versions for provider oracle/oci:
locked provider registry.terraform.io/oracle/oci 4.96.0 does not match
configured version constraint 5.1.0; must use terraform init -upgrade to
allow selection of new versions

```

![image](https://github.com/oracle-quickstart/oci-landing-zones/assets/97471415/bbdfb3bc-0489-4624-b2c8-38acdcc6d5a5)

**Comment by paulmuah** [comment]
Hey @mike-leuer, we are tracking this under ISSUE-1899. I will keep you informed of our progress.

**Comment by paulmuah** [comment]
Hey @mike-leuer, we were triaging this issue, but were needing additional details from you.  
1. How was the old stack attached to the new template? 
3. Somehow, the entire steps that you followed so that we can attempt to re-create this issue.

**Comment by mike-leuer** [comment]
1. I am using the latest template; however, I had originally deployed the stack with a older version.

**Comment by mike-leuer** [comment]
2. Deploy the old commit using oracle stacks console
https://github.com/oracle-quickstart/oci-landing-zones/commit/1093ec0ca270edcfda64e281e38b9ffde289a56f
3. Deploy the latest commit
The error happens

**Comment by paulmuah** [comment]
@mike-leuer this issue is intermittent and terraform init will resolve this .
