### ISSUE TITLE
With bastion service disabled terraform fails with prod_bastion_client_cidr_block_allow_list error

### ISSUE THREAD

**Issue by calorbeer** [oracle-quickstart/oci-landing-zones#58]
With bastion service disabled terraform plan for enterprise-landing-zone and freetrail-landing-zone fail with

Error: No value for required variable
  on variables.tf line 249:
 249: variable "prod_bastion_client_cidr_block_allow_list" {
The root module input variable "prod_bastion_client_cidr_block_allow_list" is
not set, and has no default value. Use a -var or -var-file command line
argument to provide a value for this variable.

**Comment by VinayKumar611** [comment]
Hey @calorbeer , 

Thanks for reporting issue. We had replicated the issue and working on the fix . We will provide the update on this asap.

**Comment by VinayKumar611** [comment]
Fixed the issue on latest release v2.2.0.
