### ISSUE TITLE
destroy_lz.py script times out on log analytics removal

### ISSUE THREAD

**Issue by shahriar-shafiullah** [oracle-quickstart/oci-landing-zones#59]
Hi,
I continuously see this error when running the destroy_lz.py script located under templates/enterprise-landing-zone/

`python3 destroy_lz.py -r SJC -e P -c MAIN-CMP-HOME2
beginning env P destroy
fetching compartment ids
beginning service connector destroy
beginning bucket destroy
beginning log analytics destroy
Traceback (most recent call last):
  File "/Users/shahriar.shafiullah/oci/oci-landing-zones/templates/enterprise-landing-zone/destroy_lz.py", line 433, in <module>
    destroy_lz.delete_environment(env)
  File "/Users/shahriar.shafiullah/oci/oci-landing-zones/templates/enterprise-landing-zone/destroy_lz.py", line 314, in delete_environment
    self.purge_log_analytics(compartments["security"])
  File "/Users/shahriar.shafiullah/oci/oci-landing-zones/templates/enterprise-landing-zone/destroy_lz.py", line 215, in purge_log_analytics
    waiter_result = oci.wait_until(
                    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/oci/waiter.py", line 113, in wait_until
    raise MaximumWaitTimeExceeded('Maximum wait time has been exceeded.')
oci.exceptions.MaximumWaitTimeExceeded: Maximum wait time has been exceeded.`

**Comment by shahriar-shafiullah** [comment]
Some more information on this, we are on a 'pay as you go' type tenancy in case that is relevant

**Comment by paulmuah** [comment]
Hey @shahriar-shafiullah, we've been in contact with someone from your account team regarding this issue. Some feedback was communicated to them. Please let me know some feedback once you've implemented the recommendations.

**Comment by jmalbarranORA** [comment]
Same issue solved. See my issue #71

**Comment by paulmuah** [comment]
Hey @shahriar-shafiullah, we are working on this currently. The Tracking is **ISSUE1922** . I will keep you updated once the new release is available.

**Comment by VinayKumar611** [comment]
Hi @shahriar-shafiullah , 

We have added logging Analytic Policy , that will help to mitigate this issue. Please use the latest version v2.1.2
