### ISSUE TITLE
Reorg of OELZ v2 documentations

### ISSUE THREAD

**Issue by fabiob77** [oracle-quickstart/oci-landing-zones#6]
I think it would be important to move the current documentation available within the template called enterprise Landing Zone to the root section of the repo. The root section of the repo should have a folder called docs where it will be possible to find all documents relating to the LZ. The Landing Zone documents should also have a naming convention to be easily identifiable

**Comment by paulmuah** [comment]
Hey @fabiob77 , we are tracking this issue with LANZ-1288

**Comment by VinayKumar611** [comment]
Fixed the Documentation Hierarchy on latest release v2.2.0.

**Comment by VinayKumar611** [comment]
Fixed the Documentation Hierarchy on latest release v2.2.0.

**Comment by VinayKumar611** [comment]
Fixed the Documentation Hierarchy on latest release v2.2.0.
