### ISSUE TITLE
tagging limit

### ISSUE THREAD

**Issue by mike-leuer** [oracle-quickstart/oci-landing-zones#61]
Error: 409-TenantCapacityExceeded, Maximum number of tagDefault [20] reached in compartment 

Suggestion: The resource is in a conflicted state. Please retry again or contact support for help with service: Identity Tag Default
Requested Information

Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/identity_tag_default
API Reference: https://docs.oracle.com/iaas/api/#/en/identity/20160918/TagDefault/CreateTagDefault
Request Target: POST https://identity.us-ashburn-1.oci.oraclecloud.com/20160918/tagDefaults
Provider version: 5.1.0, released on 2023-06-13. This provider is 3 Update(s) behind to current.
Service: Identity Tag Default
Operation Name: CreateTagDefault

**Comment by paulmuah** [comment]
Hey @mike-leuer, we've resolved this issue in the version that we'll release. I'll let you know the release date shortly. Many thanks for all your positive feedback and suggestions.

**Comment by mike-leuer** [comment]
I am trying out the latest now.

**Comment by VinayKumar611** [comment]
Hi @mike-leuer , 

We had fixed this issue , please use the latest version v2.1.1.
