### ISSUE TITLE
Security + OCI Administrators  architecture  Question

### ISSUE THREAD

**Issue by mike-leuer** [oracle-quickstart/oci-landing-zones#69]
How does Administrators in OCI correspond to the user groups? How should we manage the two? They seem related to what the oci landing zone has?

https://docs.oracle.com/en/cloud/paas/identity-cloud/uaids/understand-administrator-roles.html#GUID-9B488723-43A1-47B1-ACB0-41FFD780FD5D
![image](https://github.com/oracle-quickstart/oci-landing-zones/assets/97471415/c1d63977-b31d-4b8e-bdec-cdb1a4c35176)

**Verses**

**Network Admin: ** User group that have access to the network resources inside your environment
**SecOps Admin: ** User group that have access to the security related resources inside your environment
**Identity Admin: ** User group that can manage the identity related resources
**Platform Admin: ** User group that have access to usage reports and can manage budgets
**Ops Admin: ** User group that have access to the metrics, events and alerts in your environment
**Log Admin: ** User group that have access to the logs of your environment

**Comment by fabiob77** [comment]
Our admin groups are not a 1:1 mapping to the IDCS Admin groups, we are going to update our documentation to be more explicit about it.

**Comment by fabiob77** [comment]
@paulmuah , can we create an internal Ticket to improve the documentation?

**Comment by paulmuah** [comment]
Hey @fabiob77  @mike-leuer , we will track this under **ISSUE1945**

**Comment by VinayKumar611** [comment]
Fixed the issue on latest release v2.2.0.
