### ISSUE TITLE
Policies required for destroy landing zone

### ISSUE THREAD

**Issue by jmalbarranORA** [oracle-quickstart/oci-landing-zones#71]
I had several problems when I want to delete a landing zone, but one very specific is to delete the log groups.
Finally, the support team found the root cause. 
We need to add the following 2 policies to parent compartment for Log Groups

```
allow service loganalytics to manage loganalytics-features-family in tenancy
allow service loganalytics to manage loganalytics-resources-family in tenancy
```

**Comment by fabiob77** [comment]
Thanks @jmalbarranORA for the feedback, We added it to our backlog and the change will be implemented in the next releases.

**Comment by VinayKumar611** [comment]
Hi @jmalbarranORA 

Added these policy on latest version. Please check new version https://github.com/oracle-quickstart/oci-landing-zones/tree/v2.1.2
