### ISSUE TITLE
ORM deployment fail

### ISSUE THREAD

**Issue by fabiob77** [oracle-quickstart/oci-landing-zones#72]
I am trying to deploy the OELZ using ORM (I just downloaded the code from Github repo and use it within ORM)  but I got this error during the deployment.  "Error: 409-NotAuthorizedOrResourceAlreadyExists, Compartment -:  ocid1.tenancy.oc1..aaaaaaaavgvnnjx74fkruavau43g56srimxrgl6tsip4zmzrfbembhxsbbca already attached"
![image](https://github.com/oracle-quickstart/oci-landing-zones/assets/32541240/b18a5de8-eba6-4053-a900-4b416355e438)

**Comment by VinayKumar611** [comment]
Hi @fabiob77 , 

Thanks for providing your feedback , but this error 409 suggest the Cloud Guard target are already configured in the tenancy. Please check your tenancy resources.
