### ISSUE TITLE
Issue deploying to a brand new tenancy

### ISSUE THREAD

**Issue by liamhelmer** [oracle-quickstart/oci-landing-zones#89]
Working with @VinayKumar611 to fix this issue.

New tenancy, no extra workloads, basic configuration, audit logging enabled.

module.prod_environment.module.logging.time_sleep.first_log_delay: Still creating... [9m50s elapsed]
module.prod_environment.module.logging.time_sleep.first_log_delay: Creation complete after 10m0s [id=2023-08-18T22:41:07Z]
module.prod_environment.module.logging.module.default_log_service_connector[0].data.oci_objectstorage_namespace.ns: Reading...
module.prod_environment.module.logging.module.default_log_service_connector[0].data.oci_objectstorage_namespace.ns: Read complete after 0s [id=ObjectStorageNamespaceDataSource-4127941062]
module.prod_environment.module.logging.module.default_log_service_connector[0].oci_sch_service_connector.service_connector: Creating...
module.prod_environment.module.logging.module.default_log_service_connector[0].oci_sch_service_connector.service_connector: Creation complete after 1s [id=ocid1.serviceconnector.oc1.ca-toronto-1.amaaaaaau3qpujqa2m4jx76pusihwynr7nonvypb5fft4zf4ahafm3y73kwq]
╷
│ Error: 400-InvalidParameter, Compartment {ocid1.compartment.oc1..aaaaaaaaletun5px36t6dydhebcbb4lm7nldl6k5varh4fk7zrfn4qemixvq} does not exist or is not part of the policy compartment subtree
│ Suggestion: Please update the parameter(s) in the Terraform config as per error message Compartment {ocid1.compartment.oc1..aaaaaaaaletun5px36t6dydhebcbb4lm7nldl6k5varh4fk7zrfn4qemixvq} does not exist or is not part of the policy compartment subtree
│ Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/identity_policy 
│ API Reference: https://docs.oracle.com/iaas/api/#/en/identity/20160918/Policy/CreatePolicy 
│ Request Target: POST https://identity.ca-toronto-1.oci.oraclecloud.com/20160918/policies 
│ Provider version: 5.1.0, released on 2023-06-13. This provider is 9 Update(s) behind to current. 
│ Service: Identity Policy 
│ Operation Name: CreatePolicy 
│ OPC request ID: b65afc5d48d45cbd44c0211497c4b9d8/5AD54644A46A416709373920CFCC004C/4F0D5B01F0AE9EC0FA4D002184DC1FE3 
│ 
│ 
│   with module.prod_environment.module.workload.module.workload_osms_dg_policy.oci_identity_policy.policy,
│   on ../../modules/policies/main.tf line 9, in resource "oci_identity_policy" "policy":
│    9: resource "oci_identity_policy" "policy" {
│ 
╵
╷
│ Error: 400-InvalidParameter, Compartment {ocid1.compartment.oc1..aaaaaaaa4vadzl5se5w5dcjmhuq7bcxzv3lqrttblqmrxp42f3cpxpl6se4a} does not exist or is not part of the policy compartment subtree
│ Suggestion: Please update the parameter(s) in the Terraform config as per error message Compartment {ocid1.compartment.oc1..aaaaaaaa4vadzl5se5w5dcjmhuq7bcxzv3lqrttblqmrxp42f3cpxpl6se4a} does not exist or is not part of the policy compartment subtree
│ Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/identity_policy 
│ API Reference: https://docs.oracle.com/iaas/api/#/en/identity/20160918/Policy/CreatePolicy 
│ Request Target: POST https://identity.ca-toronto-1.oci.oraclecloud.com/20160918/policies 
│ Provider version: 5.1.0, released on 2023-06-13. This provider is 9 Update(s) behind to current. 
│ Service: Identity Policy 
│ Operation Name: CreatePolicy 
│ OPC request ID: 77f87e3624e0a5f8e10b1bbded09796f/78CCD9014C71D8656AEF81ABA3FBB260/67188E7CD163DB02AB4676A44D92C4E8 
│ 
│ 
│   with module.nonprod_environment.module.workload.module.workload_osms_dg_policy.oci_identity_policy.policy,
│   on ../../modules/policies/main.tf line 9, in resource "oci_identity_policy" "policy":
│    9: resource "oci_identity_policy" "policy" {
│ 
╵

**Comment by VinayKumar611** [comment]
Hi @liamhelmer , 

Thanks for sharing your feedback.  The main branch where you had taken the code doesn't have the current workload issue fix.

Please download the file "templates/elz-workload/security.tf " from the integration branch using the undermentioned weblink.
This branch has the fix for the issue that you had encountered.

https://github.com/oracle-quickstart/oci-landing-zones/blob/integration/templates/elz-workload/security.tf
