### ISSUE TITLE
GitHub Configuration source provider for Resource Manager does not find landing zone repository

### ISSUE THREAD

**Issue by markuszellneroraclecom** [oracle-quickstart/oci-landing-zones#94]
I have configured a GitHub Configuration source provider for Resource Manager and successfully tested the connection to GitHub.

I have generated a PAT (Personal Access Token) with scope "repo" in GitHub.

However there are no repositories appearing when attempting to create the Stack.
![image](https://github.com/oracle-quickstart/oci-landing-zones/assets/143408948/77271834-7dc7-4bcf-aa23-d13120b57bbc)
![image](https://github.com/oracle-quickstart/oci-landing-zones/assets/143408948/b224f245-60a9-47b9-b491-eb161680487f)
![image](https://github.com/oracle-quickstart/oci-landing-zones/assets/143408948/a34b9245-1db0-4769-bd87-5467618cabd0)

**Comment by fabiob77** [comment]
the resolution of the problem was to fork the GitHub repository https://github.com/oracle-quickstart/oci-landing-zones.git into the personal GitHub repository  https://github.com/markuszellneroraclecom/oci-landing-zones.git
