### ISSUE TITLE
Oracle Cloudworld

### ISSUE THREAD

**Issue by mike-leuer** [oracle-quickstart/oci-landing-zones#98]
Will any of the team be at cloud world? Also is there any talks using oci-landing-zones?

**Comment by fabiob77** [comment]
Good Morning Mike, thank for your message. Our team will not be present at Cloud World but there should be a team we worked with that will present the SCCA LZ (https://github.com/oracle-quickstart/oci-scca-landingzone). In case you would like to have a dedicated chat with us we are happy to organise it, just let us know. 

Kind regards,

Fabio
